# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.Tag')),
                ('scheduled_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('local', models.CharField(blank=True, max_length=200)),
                ('status', models.IntegerField()),
                ('is_fixed', models.BooleanField()),
            ],
        ),
    ]
